#!/bin/sh
DAEMON_NAME="aesdsocket"
DAEMON_PATH="/usr/bin/aesdsocket"

case "$1" in
  start)
    echo "Starting $DAEMON_NAME..."
    start-stop-daemon  -S -n $DAEMON_NAME -a $DAEMON_PATH -- -d
    ;;
  stop)
    echo "Stopping $DAEMON_NAME..."
    start-stop-daemon -K -n $DAEMON_NAME
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
